spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo
  
#spring.datasource.url: jdbc:mysql://192.168.1.4:3306/test  
#spring.datasource.username: javatpoint  
#spring.datasource.password: password  


employee.baseUrl: https://run.mocky.io
  
  
 